import { Header } from '@/components/header/Header'
import './globals.scss'
import { Inter } from 'next/font/google'
import { SidePanel } from '@/components/layouts/side-panel/SidePanel'
import { ListContainer } from '@/components/core/list-container/ListContainer'
import { Post } from '@/types'
import BlogPageService from '@/services/blog/blogPage'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />

        {/* Layout for page */}
        <div className='page-layout'>

          {/* Layout for page content */}
          <div className='page-content'>
            {children}
          </div>

          {/* Layout for side panel */}
          <SidePanel>
            <ListContainer title='Sidebar'>
              <>
                <li>New Blogs Coming Soon</li>
              </>
            </ListContainer>
          </SidePanel>

        </div>
      </body>
    </html>
  )
}
