import { Header } from '@/components/header/Header'
import './globals.scss'
import { Inter } from 'next/font/google'
import { SidePanel } from '@/components/layouts/side-panel/SidePanel'
import { ListContainer } from '@/components/core/list-container/ListContainer'
import Script from 'next/script'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Script src="https://www.googletagmanager.com/gtag/js?id=G-W9CVD1Y1EF" />
      <Script id="google-analytics">
        {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
 
          gtag('config', 'G-W9CVD1Y1EF');
        `}
      </Script>
      <body className={inter.className}>

        <Header />

        {/* Layout for page */}
        <div className='page-layout'>

          {/* Layout for page content */}
          <div className='page-content'>
            {children}
          </div>

          {/* Layout for side panel */}
          <SidePanel>
            <ListContainer title='Sidebar' className='sidebar'>
              <>
                <li>New Blogs Coming Soon</li>
              </>
            </ListContainer>
          </SidePanel>

        </div>
      </body>
    </html>
  )
}
